-------------------------------------------------------------------------------
Test set: users.management.UsersManagementFacadeServiceTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.394 s <<< FAILURE! -- in users.management.UsersManagementFacadeServiceTest
users.management.UsersManagementFacadeServiceTest.createUserWithCompanyShouldNotThrow -- Time elapsed: 0.369 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Unexpected exception thrown: org.mockito.exceptions.misusing.PotentialStubbingProblem: 
Strict stubbing argument mismatch. Please check:
 - this invocation of 'create' method:
    userService.create(
    UserFormDTO[name=name1, password=password1, confirmationPassword=password1, surname=surname1, email=email1@test.pl, role=role1, phoneNumber=123123111, companyID=4909b452-2532-40e2-9356-f5e77cb609bf, addressFormDTO=AddressFormDTO[addressID=a5e7cde6-a752-4b1f-b363-28e4d5561f42, town=town, postalCode=postalCode, houseNumber=houseNumber, apartmentNumber=apartmentNumber, city=city, street=street], userSettingsFormDTO=UserSettingsFormDTO[smsNotification=false, appNotification=true, emailNotification=false]],
    null,
    users.management.entity.Company@ba562e0
);
    -> at users.management.UsersManagementFacade.createUser(UsersManagementFacade.java:37)
 - has following stubbing(s) with different arguments:
    1. userService.create(null, null, null);
      -> at users.management.UsersManagementFacadeServiceTest.createUserWithCompanyShouldNotThrow(UsersManagementFacadeServiceTest.java:58)
Typically, stubbing argument mismatch indicates user mistake when writing tests.
Mockito fails early so that you can debug potential problem easily.
However, there are legit scenarios when this exception generates false negative signal:
  - stubbing the same method multiple times using 'given().will()' or 'when().then()' API
    Please use 'will().given()' or 'doReturn().when()' API for stubbing.
  - stubbed method is intentionally invoked with different arguments by code under test
    Please use default or 'silent' JUnit Rule (equivalent of Strictness.LENIENT).
For more information see javadoc for PotentialStubbingProblem class.
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:84)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:53)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:36)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3199)
	at users.management.UsersManagementFacadeServiceTest.createUserWithCompanyShouldNotThrow(UsersManagementFacadeServiceTest.java:61)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.mockito.exceptions.misusing.PotentialStubbingProblem: 
Strict stubbing argument mismatch. Please check:
 - this invocation of 'create' method:
    userService.create(
    UserFormDTO[name=name1, password=password1, confirmationPassword=password1, surname=surname1, email=email1@test.pl, role=role1, phoneNumber=123123111, companyID=4909b452-2532-40e2-9356-f5e77cb609bf, addressFormDTO=AddressFormDTO[addressID=a5e7cde6-a752-4b1f-b363-28e4d5561f42, town=town, postalCode=postalCode, houseNumber=houseNumber, apartmentNumber=apartmentNumber, city=city, street=street], userSettingsFormDTO=UserSettingsFormDTO[smsNotification=false, appNotification=true, emailNotification=false]],
    null,
    users.management.entity.Company@ba562e0
);
    -> at users.management.UsersManagementFacade.createUser(UsersManagementFacade.java:37)
 - has following stubbing(s) with different arguments:
    1. userService.create(null, null, null);
      -> at users.management.UsersManagementFacadeServiceTest.createUserWithCompanyShouldNotThrow(UsersManagementFacadeServiceTest.java:58)
Typically, stubbing argument mismatch indicates user mistake when writing tests.
Mockito fails early so that you can debug potential problem easily.
However, there are legit scenarios when this exception generates false negative signal:
  - stubbing the same method multiple times using 'given().will()' or 'when().then()' API
    Please use 'will().given()' or 'doReturn().when()' API for stubbing.
  - stubbed method is intentionally invoked with different arguments by code under test
    Please use default or 'silent' JUnit Rule (equivalent of Strictness.LENIENT).
For more information see javadoc for PotentialStubbingProblem class.
	at users.management.service.UserService.create(UserService.java:43)
	at users.management.UsersManagementFacade.createUser(UsersManagementFacade.java:37)
	at users.management.UsersManagementFacadeServiceTest.lambda$createUserWithCompanyShouldNotThrow$1(UsersManagementFacadeServiceTest.java:61)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:49)
	... 6 more

